# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShutterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shutter_name', models.CharField(max_length=100)),
                ('upside_down', models.BooleanField()),
                ('power_output_adress', models.PositiveSmallIntegerField(unique=True)),
                ('direction_selector_adress', models.PositiveSmallIntegerField(unique=True)),
                ('opened_from_middle_timer', models.DurationField()),
                ('opened_from_closed_timer', models.DurationField()),
                ('middle_from_opened_timer', models.DurationField()),
                ('middle_from_closed_timer', models.DurationField()),
                ('closed_from_middle_timer', models.DurationField()),
                ('closed_from_opened_timer', models.DurationField()),
                ('running', models.BooleanField()),
                ('current_position', models.CharField(blank=True, choices=[('opened', 'Opened'), ('middle', 'Shadow'), ('closed', 'Closed')], default=None, max_length=50, null=True)),
                ('target_position', models.CharField(choices=[('opened', 'Opened'), ('middle', 'Shadow'), ('closed', 'Closed')], default='closed', max_length=50)),
                ('target_position_arrival_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
