# Generated by Django 2.2 on 2019-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shutter_name', models.CharField(max_length=100)),
                ('upside_down', models.BooleanField()),
                ('power_output_adress', models.PositiveSmallIntegerField(unique=True)),
                ('direction_selector_adress', models.PositiveSmallIntegerField(unique=True)),
                ('opened_from_middle_timer', models.DurationField()),
                ('opened_from_closed_timer', models.DurationField()),
                ('middle_from_opened_timer', models.DurationField()),
                ('middle_from_closed_timer', models.DurationField()),
                ('closed_from_middle_timer', models.DurationField()),
                ('closed_from_opened_timer', models.DurationField()),
                ('running', models.BooleanField(verbose_name='Running')),
                ('current_position', models.CharField(blank=True, choices=[('opened', 'Opened'), ('middle', 'Shadowing'), ('closed', 'Closed')], default=None, max_length=50, null=True, verbose_name='Current position')),
                ('target_position', models.CharField(choices=[('opened', 'Opened'), ('middle', 'Shadowing'), ('closed', 'Closed')], default='closed', max_length=50, verbose_name='Target position')),
                ('target_position_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Target position arrival time')),
            ],
            options={
                'ordering': ['shutter_name'],
            },
        ),
    ]

